site_name: Mathematics Notes

repo_name: arnold518/math-notes

repo_url: https://github.com/arnold518/math-notes

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: material/lightbulb-on
      tip: fontawesome/solid/clock
  language: ko  
  font:
    text: Noto Sans
    code: Ubuntu Mono
  palette: 
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: green
        accent: green
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: green
        accent: green
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arnold518
  generator: false

nav:
  - Home: index.md
  - Abstract Algebra:
      - abstract-algebra/index.md
      - 0. Sets and Relations : abstract-algebra/0.md
      - Ch 1. Groups and SubGroups:
          - 1. Introduction and Examples : abstract-algebra/1.md
          - 2. Binary Operations : abstract-algebra/2.md
          - 3. Isomorphic Binary Structures : abstract-algebra/3.md
          - 4. Groups : abstract-algebra/4.md
          - 5. Subgroups : abstract-algebra/5.md
          - 6. Cyclic Groups : abstract-algebra/6.md
          - 7. Generating Sets and Cayley Digraphs : abstract-algebra/7.md
      - Ch 2. Permutations, Cosets, and Direct Products : 
          - 8. Groups of Permutations : abstract-algebra/8.md
          - 9. Orbits, Cycles, and the Alternating Groups : abstract-algebra/9.md
          - 10. Cosets and the Theorem of Lagrange : abstract-algebra/10.md
          - 11. Direct Products and Finitely Generated Abelian Groups : abstract-algebra/11.md
          - 12. Plane Isometries : abstract-algebra/12.md
      - Ch 3. Homomorphisms and Factor Groups : 
          - 13. Homomorphisms : abstract-algebra/13.md
          - 14. Factor Groups : abstract-algebra/14.md
          - 15. Factor-Group Computations and Simple Groups : abstract-algebra/15.md
          - 16. Group Action on a Set : abstract-algebra/16.md
          - 17. Applications of G-Sets to Counting : abstract-algebra/17.md
      - Ch 4. Rings and Fields :
          - 18. Rings and Fields : abstract-algebra/18.md
          - 19. Integral Domains : abstract-algebra/19.md
          - 20. Fermat's and Euler's Theorem : abstract-algebra/20.md
          - 21. The Field of Quotients of an Integral Domain : abstract-algebra/21.md
          - 22. Rings of Polynomials : abstract-algebra/22.md
          - 23. Factorization of Polynomials over a Field : abstract-algebra/23.md
          - 24. Noncommutative Examples : abstract-algebra/24.md
          - 25. Ordered Rings and Fields : abstract-algebra/25.md
  - Topology:
      - topology/index.md
      - Ch 1. Set Theory and Logic:
          - 1. Fundamental Concepts : topology/1.md
          - 2. Functions : topology/2.md
          - 3. Relations : topology/3.md
          - 4. The Integers and the Real Numbers : topology/4.md
          - 5. Cartesian Products : topology/5.md
          - 6. Finite Sets : topology/6.md
      - Ch 2. Topological Spaces and Continuous Functions:
          - 12. Topological Spaces : topology/12.md
          - 13. Basis for a Topology : topology/13.md
          - 14. The Order Topology : topology/14.md
          - 15. The Product Topology on X тип Y : topology/15.md
          - 16. The Subspace Topology : topology/16.md
          - 17. Closed Sets and Limit Points : topology/17.md
          - 18. Continuous Functions : topology/18.md
          - 19. The Product Topology : topology/19.md
          - 20. The Metric Topology : topology/20.md
          - 21. The Metric Topology (continued) : topology/21.md
          - 22. The Quotient Topology : topology/22.md
      - Ch 3. Connectedness and Compactness:
          - 23. Connected Spaces : topology/23.md
          - 24. Connected Subspaces of the Real Line : topology/24.md
          - 25. Components and Local Connectedness : topology/25.md
          - 26. Compact Spaces : topology/26.md
          - 27. Compact Subspaces of the Real Line : topology/27.md
          - 28. Limit Point Compactness : topology/28.md
          - 29. Local Compactness : topology/29.md
  - Mathematical Foundations of Deep Neural Networks:
      - mfdnn/format/index.md
      - Ch 1. Optimization and Stochastic Gradient Descent:
          - 1. Optimization Problem : mfdnn/format/1.md
          - 2. Gradient Descent: mfdnn/format/2.md
          - Chapter 1 Code: https://drive.google.com/file/d/1PSpoeseUPIptYQOPuQpxNawxtZbVR_K6/view?usp=sharing
      - Ch 2. Shallow Neural Networks to Multilayer Perceptrons:
          - 3. Shallow Neural Networks : mfdnn/format/3.md
          - 4. Deep Neural Networks : mfdnn/format/4.md
          - Chapter 2 Code: https://drive.google.com/file/d/15kXC3cJUV63gZNfXK6JdPPuSrwQZBzI8/view?usp=sharing
      - Ch 3. Convolutional Neural Networks:
          - 5. Convolutional Neural Networks : mfdnn/format/5.md
          - 6. Foundations of Design and Training of Deep Neural Networks : mfdnn/format/6.md
          - 7. ImageNet Challenge : mfdnn/format/7.md
          - Chapter 3 Code: https://drive.google.com/file/d/12O9fLasWDA-kOKBD-lE-1UhCl-PoDf0z/view?usp=sharing
      - Ch 4. CNNs for Other Supervised Learning Tasks:
          - 8. CNNs for Other Supervised Learning Tasks : mfdnn/format/8.md
          - Chapter 4 Code: https://drive.google.com/file/d/16IOKVF6IiDMyUvL73pGKBaEMKyXvezLB/view?usp=sharing
      - Ch 5. Unsupervised Learning:
          - 9. Autoencoder : mfdnn/format/9.md
          - 10. Flow Models : mfdnn/format/10.md
          - 11. Variational Autoencoders : mfdnn/format/11.md
          - 12. Generative Adversarial Networks : mfdnn/format/12.md
          - Chapter 5 Code: https://drive.google.com/file/d/1JM5k-e6LkhZ0vXRlfROWpiuw4YC85Jv1/view?usp=sharing
      - Ch A. Appendix - Basics of Monte Carlo:
          - 13. Basics of Monte Carlo : mfdnn/format/13.md
          - Chapter A Code: https://drive.google.com/file/d/18b01xoORd0LFQmpfc_4ou5Rv44MY1neg/view?usp=sharing
      - Python Basics:
          - Python Lecture 1: https://drive.google.com/file/d/1-iY9XfDhWNRDq3z_wVVvOzU04aRQWAfW/view?usp=drive_link
          - Python Lecture 2: https://drive.google.com/file/d/1BANbCC6jBjPEUFSRJMFkcLbc4oVmoQHm/view?usp=sharing
          - Python Lecture 3: https://drive.google.com/file/d/1-Bc11RZmno6yx37kfVLjsyY-XKpLK5Je/view?usp=drive_link